version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: digilinq/platform/user-service
    container_name: user-service
    networks:
      - digilinq-network
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
networks:
  digilinq-network:
    name: digilinq
    external: true