version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TEST_DB=${TEST_DATABASE}
      - TEST_USER=${TEST_USERNAME}
      - TEST_PASSWORD=${TEST_PASSWORD}
    networks:
      - tech-innovative-network

networks:
  tech-innovative-network:
    name: tech-innovative
    external: false
