#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USERNAME" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$TEST_USER" WITH PASSWORD '$TEST_PASSWORD';
  CREATE DATABASE "$TEST_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$TEST_DB" TO "$TEST_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$TEST_USER" --dbname "$TEST_DB" <<-EOSQL
	CREATE SCHEMA users;
EOSQL

