apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: users-ms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-ms
        app: users-ms
    spec:
      containers:
        - name: users
          image: docker.io/digilinq/users-microservice
          env:
            - name: APP_VERSION
              value: "1.0.0"
          envFrom:
            - configMapRef:
                name: users-config
          ports:
            - containerPort: 8080
              name: service
            - containerPort: 8081
              name: management
          resources: {}
      restartPolicy: Always