apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: users
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: service
    - name: management
      port: 8081
      protocol: TCP
      targetPort: management
