apiVersion: v1
kind: Service
metadata:
  name: users-ms
spec:
  selector:
    app.kubernetes.io/name: users-ms
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: management
      port: 8081
      protocol: TCP
      targetPort: management
  type: ClusterIP
