spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/infinite_tech?currentSchema=users
    username: infinite_tech
    password: NPXkk0xUTJCfnrAR
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
eureka:
  client:
    enabled: false

mail:
  smtp:
    host: smtp-relay.brevo.com
    port: 587
    username:
    password:
