---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/digilinq
    username: digilinq
    password: 123456
    driver-class-name: org.postgresql.Driver
---