logging:
  level:
    root: INFO
#    org.springframework.web: INFO
#    org.hibernate: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/tech-innovative
    username: tech-innovative
    password: tech-innovative
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
---
