name: Java CI

on: [push]

jobs:
  build:
    name: Build maven project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp web/target/*.jar staging
      - run: cp deployment/Dockerfile staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

  create-docker-image:
    name: Create docker image and push to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - build
#    permissions:
#      contents: read
#      packages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Package
      - name: Login to container repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.REGISTRY }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metdata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
