# job1: detect vulnerabilities
# job2: clean code and code smells and test coverage with sonar
# job3: code quality with sigrid
name: Code quality check
on: [push]
jobs:
  detect-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      -
        name: Print Event Name
        run: >-
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Name: ${{ github.event_name }}"

