name: Build maven project using reusable workflows
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build-maven-project:
    uses: digilinq/reusable-workflows/.github/workflows/build-maven-project.yaml@t1
