name: Build maven project using reusable workflows
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build:
    uses: digilinq/reusable-workflows/.github/workflows/build-maven-project.yaml@t3
    with:
      runner: ubuntu-latest
      ref: ${{ github.ref }}
      java-version: '17'
      maven-version: '3.8.2'
