name: Build maven project using reusable workflows
on:
  push:
    branches:
      - 'feature/*'
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      item1: ${{ steps.run_tests.outputs.item1 }}
    steps:
      - name: Effective config
        run: jq -V
      - name: Check event name
        id: event
        run: echo "event_name=${{ github.event_name }}" >> "$GITHUB_OUTPUT"
      - name: Run tests
        run: |
          echo "item1=value1" >> $GITHUB_OUTPUT
          echo "item2=value2" >> $GITHUB_OUTPUT
        id: run_tests
        env:
          MIX_ENV: test
          PGHOST: localhost
          PGUSER: postgres
      - name: Print SLACK_MESSAGE env
        env:
          ITEM_ONE: ${{ steps.run_tests.outputs.item1 }}
          SLACK_MESSAGE: ${{ join(steps.run_tests.outputs.*, '\n') }}
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: echo $ITEM_ONE

  validate:
    needs:
      - config
    runs-on: ubuntu-latest
    steps:
      - name: Print Item 1
        run: echo ${{ needs.config.outputs.item1 }}

  build:
    uses: digilinq/reusable-workflows/.github/workflows/build-maven-project.yaml@t3
    needs:
      - config
    with:
      runner: ubuntu-latest
      ref: ${{ github.ref }}
      java-version: '17'
      maven-version: '3.8.2'
