name: Feature branch events
on:
  push:
    branches:
      - 'feature/*'
      - '*'
      - '!main'
  pull_request:
    branches:
      - '!master'
      - '!main'
      - 'feature/*'
jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      -
        name: Print feature branch name
        if: github.ref != 'main' && github.ref != 'master'
        run: |          
          echo "The ref is ${{ github.ref }}"
      -
        name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
