name: Build artifact and push
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '*'
      - '!main'
jobs:
  build:
    uses: digilinq/reusable-workflows/.github/workflows/build-maven-project.yaml@v1
    with:
      runner: ubuntu-latest
      java-version: 17
