name: Build artifact and push
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
      - '*'
      - '!main'
jobs:
  build:
    uses: digilinq/reusable-workflows/.github/workflows/build-maven-project.yaml@v1
    with:
      runner: ubuntu-latest
      java-version: 17

  maven-build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

